export const LOAD_PHOTOS_REQUEST = 'LOAD_PHOTOS_REQUEST'
export const LOAD_PHOTOS_SUCCESS = 'LOAD_PHOTOS_SUCCESS'
export const LOAD_PHOTOS_FAILURE = 'LOAD_PHOTOS_FAILURE'

export const DELETE_PHOTOS_REQUEST = 'DELETE_PHOTOS_REQUEST'
export const DELETE_PHOTOS_SUCCESS = 'DELETE_PHOTOS_SUCCESS'
export const DELETE_PHOTOS_FAILURE = 'DELETE_PHOTOS_FAILURE'